//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSIMDTEntities : DbContext
    {
        public QLSIMDTEntities()
            : base("name=QLSIMDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETSD> CHITIETSDs { get; set; }
        public virtual DbSet<GIACUOC> GIACUOCs { get; set; }
        public virtual DbSet<HDCT> HDCTs { get; set; }
        public virtual DbSet<HOADONDK> HOADONDKs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<THONGTINSIM> THONGTINSIMs { get; set; }
    }
}
