//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDCT
    {
        public int MAHDCT { get; set; }
        public string IDSIM { get; set; }
        public Nullable<long> TONGTIEN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    
        public virtual THONGTINSIM THONGTINSIM { get; set; }
    }
}
