//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.THONGTINSIMs = new HashSet<THONGTINSIM>();
        }
    
        public int MAKH { get; set; }
        public string TENKH { get; set; }
        public string CMND { get; set; }
        public string NGHENGHIEP { get; set; }
        public string CHUCVU { get; set; }
        public string DIACHI { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINSIM> THONGTINSIMs { get; set; }
    }
}
